deployment:
  tasks:
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
