import type { Metadata } from "next";
import "@/app/globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';

import { UserProvider } from "./context/UserContext";
import { CartProvider } from "./context/CartContext";
import { WishlistProvider } from "./context/WishlistContext";

import ClientWrapper from "./components/common/ClientWrapper";

export const metadata: Metadata = {
  title: "Marketo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-roboto scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-gray-200">
        <UserProvider>
          <CartProvider>
            <WishlistProvider>
              <ClientWrapper>{children}</ClientWrapper>
            </WishlistProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
